### ISSUE TITLE
Atualizar documentação de importação dos recursos no terrraform.

### ISSUE THREAD

**Issue by paulohmorais** [tsuru/terraform-provider-tsuru#30]
Boa tarde pessoal, 

Ao procurar na documentação, exemplos de como usar o terraform import para os recursos tsuru. Verifiquei que ela não esta atualizada. 
Por exemplo para o recurso service_instance_bind, temos o exemplo como usar:
https://registry.terraform.io/providers/tsuru/tsuru/latest/docs/resources/service_instance_bind#import

`terraform import tsuru_service_instance_bind.my_bind "SERVICE::INSTANCE::APP"
`

Entretanto na documentação do recurso  tsuru_app não temos o exemplo para nos basear:
https://registry.terraform.io/providers/tsuru/tsuru/latest/docs/resources/app

Verifiquei que o comando abaixo funcionou no import deste recurso

``$ terraform import tsuru_app.my_app "id"``

id = Nome da app.

Se possível adicionar o exemplo em todos os recursos que o terraform import consegue nos trazer do tsuru.

**Comment by tcarreira** [comment]
A documentação foi atualizada https://registry.terraform.io/providers/tsuru/tsuru/latest/docs
Todos os resources têm exemplo de import 👍
