### ISSUE TITLE
O parameters do resource resource_tsuru_service_instance não atualiza

### ISSUE THREAD

**Issue by juliolustosa** [tsuru/terraform-provider-tsuru#32]
Ao atualizar o campo parameters o mesmo não está sendo atualizado.

https://github.com/tsuru/terraform-provider-tsuru/blob/c810515ab56056afdfa9094dfcbfbfbfd3bcc579/internal/provider/resource_tsuru_service_instance.go#L215

**Comment by tcarreira** [comment]
Não estou conseguindo replicar o problema.
O que não está sendo atualizado é o tfstate ou o resource real? Se ele atualizar o tfstate mas não atualizar o resource real, o problema pode estar na API e não no provider.
Vc tem um caso que eu possa replicar?
